// Build script for spark-storage:
//   1. Link libcuda for the raw driver FFI in cuda_min.rs.
//   2. Compile predictor CUDA kernels (.cu → .ptx) via nvcc, emit
//      `OUT_DIR/predictor_ptx.rs` so callers can `include!` to obtain the
//      PTX text at compile time.

use std::path::{Path, PathBuf};
use std::process::Command;

const KERNELS: &[&str] = &[
    "q_lowrank_project",
    "kv_lowrank_project",
    "predictor_score",
    "paged_decode_attn_tiled",
    "attention_finalize",
];

fn main() {
    link_libcuda();
    compile_kernels();
    println!("cargo:rerun-if-changed=build.rs");
}

fn link_libcuda() {
    let cuda_lib_dirs = [
        "/usr/local/cuda/targets/sbsa-linux/lib/stubs",
        "/usr/local/cuda/targets/x86_64-linux/lib/stubs",
        "/usr/local/cuda-13.0/targets/sbsa-linux/lib/stubs",
        "/usr/lib/aarch64-linux-gnu",
        "/usr/lib/x86_64-linux-gnu",
    ];
    for dir in cuda_lib_dirs {
        if Path::new(dir).is_dir() {
            println!("cargo:rustc-link-search=native={dir}");
        }
    }
    println!("cargo:rustc-link-lib=dylib=cuda");
}

fn compile_kernels() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let kernels_dir = manifest_dir.join("kernels");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let nvcc = find_nvcc();
    let arch = std::env::var("ATLAS_PREDICTOR_ARCH").unwrap_or_else(|_| "sm_121".into());

    let mut emit = String::new();
    emit.push_str("// Auto-generated by spark-storage/build.rs.\n");
    emit.push_str("pub struct StoragePtx { pub name: &'static str, pub ptx: &'static str }\n");
    emit.push_str("pub static STORAGE_PTX: &[StoragePtx] = &[\n");

    for stem in KERNELS {
        let src = kernels_dir.join(format!("{stem}.cu"));
        let ptx_out = out_dir.join(format!("{stem}.ptx"));
        println!("cargo:rerun-if-changed={}", src.display());
        let status = Command::new(&nvcc)
            .args([
                "--ptx",
                &format!("-arch={arch}"),
                "-O3",
                "--use_fast_math",
                src.to_str().unwrap(),
                "-o",
                ptx_out.to_str().unwrap(),
            ])
            .status()
            .unwrap_or_else(|e| panic!("invoke nvcc ({}): {e}", nvcc.display()));
        if !status.success() {
            panic!("nvcc --ptx failed for {}", src.display());
        }
        emit.push_str(&format!(
            "    StoragePtx {{ name: \"{stem}\", ptx: include_str!(\"{}\") }},\n",
            ptx_out.display()
        ));
    }
    emit.push_str("];\n");
    std::fs::write(out_dir.join("storage_ptx.rs"), emit).expect("emit storage_ptx.rs");
}

fn find_nvcc() -> PathBuf {
    let candidates = [
        "/usr/local/cuda/bin/nvcc",
        "/usr/local/cuda-13.0/bin/nvcc",
    ];
    for c in candidates {
        if Path::new(c).is_file() {
            return PathBuf::from(c);
        }
    }
    PathBuf::from("nvcc")
}
